# Generated by Django 5.2.7 on 2026-05-28 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rent', models.PositiveIntegerField()),
                ('security_deposit', models.PositiveIntegerField()),
                ('available_from', models.DateField()),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback image URL for seeded data')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(default='Bangalore', max_length=50)),
                ('pref_diet', models.CharField(blank=True, choices=[('veg', 'Pure Veg'), ('nonveg', 'Non-Veg'), ('vegan', 'Vegan')], max_length=20)),
                ('pref_schedule', models.CharField(blank=True, choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl')], max_length=20)),
                ('pref_pets', models.CharField(blank=True, choices=[('has_pets', 'Has Pets'), ('no_pets', 'No Pets'), ('pet_friendly', 'Pet Friendly')], max_length=20)),
                ('pref_smoking', models.CharField(blank=True, choices=[('non_smoker', 'Non-Smoker'), ('smoker', 'Smoker'), ('occasional', 'Occasional')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('nonbinary', 'Non-binary'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('is_verified', models.BooleanField(default=True)),
                ('diet', models.CharField(blank=True, choices=[('veg', 'Pure Veg'), ('nonveg', 'Non-Veg'), ('vegan', 'Vegan')], max_length=20)),
                ('schedule', models.CharField(blank=True, choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl')], max_length=20)),
                ('pets', models.CharField(blank=True, choices=[('has_pets', 'Has Pets'), ('no_pets', 'No Pets'), ('pet_friendly', 'Pet Friendly')], max_length=20)),
                ('smoking', models.CharField(blank=True, choices=[('non_smoker', 'Non-Smoker'), ('smoker', 'Smoker'), ('occasional', 'Occasional')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='platform_app.listing')),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_searcher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('listing', 'searcher')},
            },
        ),
        migrations.CreateModel(
            name='SwipeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LIKE', 'Like'), ('PASS', 'Pass')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='platform_app.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
